version: '3'

networks:

  vocnet:

services:

  database:
    image: 'postgres:latest'
    container_name: voc-db-2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./db-data/:/var/lib/postgresql/data/
    networks:
      - vocnet

  auth:
    image: 'test:auth'
    container_name: voc-auth      
    networks:
      - vocnet

  backend:
    image: 'test:api'
    container_name: voc-backend
    environment:
      QUARKUS_OAUTH2_CLIENT_ID: 0
      QUARKUS_OAUTH2_INTROSPECTION_URL: http://voc-auth:8282/oauth/introspection
      DB_HOST: voc-db-2
      DB_NAME: postgres
      DB_PASSWORD: postgres
      DB_USERNAME: postgres
    networks:
      - vocnet
    ports:
      - 8080:8080

  frontend:
    image: 'test:gui'
    container_name: voc-frontend
    environment:
      VUE_APP_APISERVER_URL: https://apis.mymiggi.de/voc-trainer/
    networks:
      - vocnet
    ports:
      - 3000:80
    
